#!/usr/bin/env php
<?php

namespace BrainGames\src\Engine;

$autoloadPath1 = __DIR__ . '/../../../autoload.php';
$autoloadPath2 = __DIR__ . '/../../vendor/autoload.php';

if (file_exists($autoloadPath1)) {
    require_once $autoloadPath1;
} else {
    require_once $autoloadPath2;
}

getStart("progression");

function startProgressionGame($userName)
{
    $maxRounds = 3;
    $correctAnswerCount = 0;
    $isCorrect = true;
    while($isCorrect && $correctAnswerCount < $maxRounds) {
        $startingNumber = mt_rand(1, 11);
        $step = mt_rand(1, 5);
        $length = 10;
        $hiddenNum = mt_rand(0,9);
        $progression = [];
        $missingValue = null;
        for ($i = 0; $i < $length;$i++ ) {
            $value = $startingNumber + $i * $step;
            if ($i == $hiddenNum) {
                $progression[] = "..";
                $missingValue = $value;
            } else {
                $progression[] = $value;
            }
        }
        $progressionToStr = implode(" ",$progression);
        echo "Question: {$progressionToStr}\nYour answer: ";
        $userAnswer = trim(fgets(STDIN));
        if ($userAnswer == $missingValue) {
            echo "Correct!\n";
            $correctAnswerCount++;
        } else {
            $isCorrect = false;
            echo("'{$userAnswer}' is wrong answer ;(. Correct answer was '{$missingValue}'\n" .
                "Let's try again, {$userName}!\n");
        }
        if ($correctAnswerCount == $maxRounds) {
            $isCorrect = false;
            echo "Congratulations, {$userName}!\n";
        }
    }
}
