#!/usr/bin/env php
<?php

namespace BrainGames\src\Engine;

use function BrainGames\src\Cli\greeting;

$autoloadPath1 = __DIR__ . '/../../../autoload.php';
$autoloadPath2 = __DIR__ . '/../../vendor/autoload.php';

if (file_exists($autoloadPath1)) {
    require_once $autoloadPath1;
} else {
    require_once $autoloadPath2;
}

getStart();

function getStart(): void
{
    $userName = greeting();
    brainGameRule('gcd');
    startGcdGame($userName);
}

function startGcdGame($userName): void
{
    $maxRounds = 3;
    $correctAnswerCount = 0;
    $isCorrect = true;
    while($isCorrect && $correctAnswerCount < $maxRounds) {
        $numGenerator1 = generateNumber();
        $numGenerator2 = generateNumber();
        echo "Question: {$numGenerator1} {$numGenerator2}\n";
        $userAnswer = trim(fgets(STDIN));
        echo "Your answer: {$userAnswer}\n";
        $correctAnswer = dividerCheck($numGenerator1, $numGenerator2);
        if ($userAnswer == $correctAnswer) {
            echo "Correct!\n";
            $correctAnswerCount++;
        } else {
            $isCorrect = false;
            echo("'{$userAnswer}' is wrong answer ;(. Correct answer was '{$correctAnswer}'\n" .
                "Let's try again, {$userName}!\n");
        }
        if ($correctAnswerCount == $maxRounds) {
            $isCorrect = false;
            echo "Congratulations, {$userName}!\n";
        }
    }
}
